apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  namespace: ifconfig
  name: ifconfig-gateway
  annotations:
    haproxy.router.openshift.io/balance: leastconn
    #haproxy.router.openshift.io/disable_cookies: "true"
    maistra.io/manageRoute: "false"

spec:
  selector:
    istio: external-ingressgateway
  servers:
    - hosts:
        - 'ifconfig.mesh.stg.stg.ethos.usw2.ctv.gg'
      port:
        name: https-external
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: ifconfig-gateway-cert
        httpsRedirect: true 
